const catMeta={rendering:{label:"Renderings",single:"Rendering"},plan:{label:"Pläne & Schnitte",single:"Plan"},modell:{label:"Modell & Prozess",single:"Modell"},detail:{label:"Details & Material",single:"Detail"}};
const marqueeWords=["Raumkonzepte","Renderings","Material & Licht","Bestand & Denkmalschutz","Möbeldesign","Lichtplanung","Corporate Interior","3D-Visualisierung","Moodboards"];
const aktDocs=[
  {tag:"Dok. 01",label:"Lageplan",src:"assets/aktuelles/plan-lageplan.jpg"},{tag:"Dok. 02",label:"Grundriss",src:"assets/aktuelles/plan-grundriss-1.jpg"},{tag:"Dok. 03",label:"Grundriss",src:"assets/aktuelles/plan-grundriss-2.jpg"},{tag:"Dok. 04",label:"Grundriss",src:"assets/aktuelles/plan-grundriss-3.jpg"},{tag:"Dok. 05",label:"Grundriss",src:"assets/aktuelles/plan-grundriss-4.jpg"},{tag:"Dok. 06",label:"Ansicht",src:"assets/aktuelles/plan-ansicht.jpg"}
];
const waldAssets=[
  {tab:"fotos",label:"Historische Ansicht",src:"assets/aktuelles/waldmannsburg-historisch.jpg"},
  {tab:"fotos",label:"Aktuelle Ansicht",src:"assets/aktuelles/waldmannsburg-heute.jpg"},
  ...aktDocs.map(d=>({tab:d.label==="Ansicht"?"schnitte":"grundrisse",label:`${d.label} - ${d.tag}`,src:d.src}))
];
const projects=[
{id:"modernisierung",title:"Modernisierung mit Feingefühl",year:"2025",type:"Bachelorarbeit",catLabel:"Interior · Bestand",role:"Bachelor-Projekt · Betreuung Prof. Yvonne Fehling",place:"Café der Badischen Landesbibliothek",programs:["VectorWorks","SketchUp","Twinmotion"],blurb:"Behutsame Modernisierung eines denkmalgeschützten Cafés - Bestand bewahren, modern weiterdenken.",concept:"Das denkmalgeschützte Café der Badischen Landesbibliothek wird modernisiert, ohne seinen Charakter zu verlieren. Historische Elemente wie rote Fassade, Fenster, Boden und Säulen bleiben erhalten und werden durch moderne, nachhaltige Eingriffe ergänzt.",measures:["Historische Substanz bewahren, moderne Nutzung ermöglichen","Schwarze Leuchtengestelle als Kontrast, auf unterschiedlichen Höhen abgehängt","Fensternischen als ruhige Rückzugsorte und zusätzliche Sitzplätze","Natürliches Licht bewusst als atmosphärisches Element integriert","Außenmöblierung nimmt Eigenschaften des Bestands auf und verbindet Innen- und Außenraum"],materials:["Terrazzo","Flexible Möblierung","Begrünung & Pflanzen","Angepasste Bestandsmöbel","Schwarze Leuchtengestelle"],result:"Ein einladendes Café, das historische Substanz, nachhaltige Materialien und zeitgemäße Nutzung harmonisch verbindet.",images:["modernisierung-01.jpeg|rendering|Außenfassade","modernisierung-03.jpeg|rendering|Café-Raum","modernisierung-04.jpeg|rendering|Innenraum","modernisierung-02.jpeg|rendering|Innenhof","modernisierung-05.jpeg|rendering|Sitzbereich","modernisierung-06.jpeg|rendering|Fensterplatz","modernisierung-07.jpeg|rendering|Theke & Terrazzo","modernisierung-08.jpeg|plan|Grundriss","modernisierung-09.jpeg|plan|Fassadenansicht","modernisierung-10.jpeg|plan|Schnitt A","modernisierung-11.jpeg|plan|Schnitt B"]},
{id:"creative-quarter",title:"Creative Quarter",year:"2024",type:"Großer Entwurf",catLabel:"Interior · Neubau",role:"Großer Entwurf · Betreuung Prof. Gregor Rutrecht",place:"Mühlenstraße, Kaiserslautern",programs:["VectorWorks","SketchUp","Twinmotion"],blurb:"Ein dreistöckiges Zentrum für Kreativität - Café, Workshops, Startups und Galerie unter einem Dach.",concept:"Das Creative Quarter ist ein dreistöckiges Zentrum für Kreativität und Innovation. Café, Workshop-Räume, Startup-Flächen und Galerie verschmelzen zu einem offenen Ort für Austausch und Zusammenarbeit.",measures:["Erdgeschoss als Café zum Entspannen und Vernetzen","Workshop-Räume und dynamische Startup-Flächen in den oberen Etagen","Galerie als Plattform für studentische Kunst und junge Talente","Grenzen zwischen Disziplinen bewusst aufheben"],materials:["Offene Raumstruktur","Helle Flächen","Galerie-Wände","Flexible Möblierung"],result:"Ein lebendiger Knotenpunkt, der Lernen, Arbeit, Austausch und Präsentation unter einem Dach verbindet.",images:["creative-quarter-02.png|rendering|Lounge & Galerie","creative-quarter-01.jpeg|modell|Axonometrie","creative-quarter-03.jpeg|plan|Grundriss EG","creative-quarter-04.jpeg|plan|Grundriss OG","creative-quarter-06.png|plan|Raumkonzept","creative-quarter-05.jpeg|plan|Schnitt","creative-quarter-07.jpg|plan|Gebäudeschnitt"]},
{id:"sparkasse",title:"Sparkasse Renovation",year:"2022",type:"Beleuchtungskonzept",catLabel:"Lighting · Renovierung",role:"Gruppenarbeit · Betreuung Prof. Alexander Klein",place:"Sparkasse Filiale",programs:["VectorWorks","SketchUp","Twinmotion"],blurb:"Ein neues Lichtkonzept für eine einladendere, angenehmere und technisch optimierte Atmosphäre.",concept:"Im Renovierungsprojekt der Sparkasse liegt der Schwerpunkt auf einem verbesserten Beleuchtungsdesign - für eine einladendere und angenehmere Atmosphäre für Kundschaft und Mitarbeitende.",measures:["Mehr natürliches Licht: vergrößerte Fenster und Oberlichter","Energieeffiziente LED-Technik mit Dimmsystemen","Tageslichtsensoren passen das Licht an Tageszeit und Nutzung an","Abgehängte Decken verbessern Akustik, Isolierung und Technikzugang"],materials:["LED-Leuchten","Tageslichtsensoren","Abgehängte Decken","Oberlichter"],result:"Ein nutzerfreundlicheres, angenehmeres und technisch optimiertes Raumkonzept mit gleichmäßiger Lichtverteilung.",images:["sparkasse-01.png|rendering|Lounge & Lamellen","sparkasse-02.png|rendering|Schnitt & Theke","sparkasse-03.png|plan|Grundriss","sparkasse-04.png|plan|Beleuchtungsplan","sparkasse-05.png|detail|Schnitt Detail","sparkasse-06.png|detail|Lichtkonzept"]},
{id:"functional-furniture",title:"Functional Furniture",year:"2022",type:"Möbeldesign",catLabel:"Furniture · Produktdesign",role:"Gruppenprojekt · Betreuung Prof. Yvonne Fehling",place:"Krankenhauszimmer",programs:["VectorWorks"],blurb:"Ein multifunktionaler Krankenhaus-Schrank - Stauraum, Licht, Arbeitstisch und Ladestation in einem.",concept:"Das Projekt entwickelt einen multifunktionalen Krankenhaus-Schrank, der sich vom sterilen Krankenhausstil abhebt und exakt in eine vorgegebene Nische passt.",measures:["Großzügiger Stauraum für persönliche und medizinische Dinge","Integrierte Beleuchtung, verstellbarer Tisch und Ladestation","Abgerundete Ecken und Kanten zur Unfallvermeidung","Langlebige, leicht zu reinigende Oberflächen"],materials:["Langlebige Oberflächen","Integrierte LED","Verstellbarer Tisch","Ladestation"],result:"Ein Möbel, das Patientenzimmer funktionaler, wohnlicher und sicherer macht - belegt durch ein handgebautes Modell.",images:["functional-furniture-01.png|rendering|Schrank im Raum","functional-furniture-02.png|modell|Handgebautes Modell","functional-furniture-03.png|plan|Konstruktion","functional-furniture-04.png|plan|Grundriss & Nische","functional-furniture-05.png|detail|Ansichten"]},
{id:"magic-marvel",title:"Magic Marvel",year:"2022",type:"Messestand",catLabel:"Exhibition · Messestand",role:"Entwurf · Betreuung Prof. Gregor Rutrecht",place:"Buchmesse / Convention",programs:["VectorWorks","SketchUp","Twinmotion"],blurb:"Ein immersiver Marvel-Stand, der schon aus der Ferne anzieht und im Inneren eine Markenwelt schafft.",concept:"Der Entwurf entwickelt einen Marvel-Stand für Buchmesse oder Convention - ein fesselnder Raum mit geheimnisvoller Fassade aus weißen Bildschirmen, auf denen lebensgroße Charaktere erscheinen.",measures:["Äußere Hülle aus weißen Bildschirmen mit Überraschungsmoment","Elegantes, modernes Interior mit Anspielungen auf Marvels Stil","Snackbar, Leseecke für Comics und Überraschungsauftritte","Obere Ebene als Planetarium - Comic-Zeichner bei der Arbeit erlebbar"],materials:["LED-Screens","Dynamische Beleuchtung","Comic-Grafiken","Lesezonen"],result:"Ein immersiver Raum, der das Marvel-Universum räumlich erfahrbar macht - von der Snackbar bis zur Erlebnisplattform.",images:["magic-marvel-01.png|rendering|Fassade & Screens","magic-marvel-02.jpeg|rendering|Leseecke","magic-marvel-03.jpeg|rendering|Snackbar"]},
{id:"tre",title:"TRE Vehicle Dynamics Interior",year:"2023-2024",type:"Corporate Interior",catLabel:"Corporate · Team Rossberg",role:"Interior Designer · Team Rossberg Engineering",place:"Team Rossberg Engineering",programs:["Moodboards","VectorWorks","Twinmotion"],blurb:"Corporate-Interior für Team Rossberg - Empfang, Büro, Pausenraum und Atrium aus vier Moodboard-Welten.",concept:"Corporate-Interior für Team Rossberg Engineering - vom Empfangsbereich über Büro und Pausenraum bis zum Atrium. Vier Moodboard-Welten bilden die gestalterische Basis.",measures:["Markenstarke Lobby mit Akustiksegeln, Holzlamellen und Trophäeninszenierung","Porsche-Büro mit Pflanzenkonzept, Mosswand und Akustikpaneelen","Pausenraum mit warmer, wohnlicher Aufenthaltsatmosphäre","Atrium als aktiver Begegnungsort mit klaren Funktionszonen"],materials:["Holzlamellen","Akustiksegel & Deckenpaneele","Mosswand & Pflanzen","Energy-Green Akzente","Terrazzo"],result:"Aus uneinheitlichen Räumen entsteht eine durchgängige, markenstarke Corporate-Welt für Team Rossberg, TRE und RXR.",images:["tre-01.jpg|rendering|Atrium & Showcar","tre-02.jpg|rendering|Empfang","tre-03.jpg|rendering|Empfang · RXR","tre-04.jpg|rendering|Empfang · Lounge","tre-05.jpg|rendering|Pausenraum","tre-06.jpg|rendering|Pausenraum · Begrünung","tre-07.jpg|rendering|Atrium · Bar","tre-08.jpg|rendering|Atrium · Lounge","tre-09.jpg|rendering|Besprechung","tre-10.jpg|rendering|Besprechung · TRE-Wand","tre-11.jpg|rendering|Besprechung · Galerie","tre-14.jpg|modell|Moodboard · Industrial","tre-15.jpg|modell|Moodboard · Mysterious Glamour","tre-16.jpg|modell|Moodboard · Scandinavian","tre-17.jpg|modell|Moodboard · Clean White","tre-18.jpg|detail|Bestand · Atrium","tre-19.jpg|detail|Bestand · Empfang","tre-12.jpg|plan|Grundriss","tre-13.jpg|plan|Markenwand"]},
{id:"dach",title:"Tradition tragen, Zukunft dämmen",year:"2025-2026",type:"Bauen im Bestand",catLabel:"Bestand · Dachsanierung",role:"Studienprojekt · Prof. Fabian A. Wagner, Ass. Louise Daussy · mit Jule Wagenbrenner",place:"Landwirtschaftliches Gebäude, Kreimbach",programs:["Bestandsanalyse","1:1-Modell","Ubakus"],blurb:"Ein historischer, ungedämmter Dachbestand - mit biobasiertem, rückbaubarem Schichtaufbau neu gedacht.",concept:"Das Projekt transformiert einen historischen Dachaufbau im Bestand: ein landwirtschaftliches Gebäude in Kreimbach mit einfacher Falzziegeldeckung, sichtbaren Eichen-Sparren und fehlender bauphysikalischer Ergänzung.",measures:["Erhalt der sichtbaren Eichen-Sparren als primäre, tragende Struktur","Diffusionsoffener, mechanisch befestigter und weitgehend reversibler Aufbau","Wiederverwendete Tonfalzziegel von F. v. Müller als äußere Witterungsschicht","Schichtfolge: Hanfbauplatte, Schilfrohr-Dämmplatte, Holzfaserplatte, Konter- und Traglattung","1:1-Modell auf Europalette mit zugeschnittenen Eichenbalken"],materials:["Wiederverwendete Tonfalzziegel","GUTEX Ultratherm Holzfaser","Hiss Reet Schilfrohr","Hemplith Hanfbauplatte","Eichen-Sparren"],result:"Denkmalnähe, Ökologie und Bauphysik werden in einem zeitgemäßen Dachsystem zusammengeführt.",images:["dach-01.jpg|detail|Bestandsdach · Eichen-Sparren","dach-02.jpg|modell|1:1-Modell · Schichtaufbau","dach-03.jpg|modell|Schichtaufbau · Detail","dach-04.jpg|detail|Tonfalzziegel · F. v. Müller","dach-05.jpg|detail|Schilfrohr-Dämmplatte","dach-06.jpg|modell|Zuschnitt Eichenbalken","dach-07.jpg|modell|Modellbau · Prozess","dach-08.jpg|modell|Schilfrohr einbauen","dach-09.jpg|plan|Bauteilaufbau & Schutzwerte","dach-10.jpg|plan|Temperaturverlauf & Taupunkt","dach-11.jpg|plan|Ökobilanz","dach-12.jpg|plan|Kostenschätzung"]}
].map((p,i)=>({...p,sheet:`PRJ-${String(i+1).padStart(2,"0")}`,images:p.images.map(s=>{const [file,cat,label]=s.split("|");return{src:`assets/projekte/${file}`,cat,label,catLabel:catMeta[cat].label,kind:"image"}})}));
const projectBentoOrder=["creative-quarter","sparkasse","functional-furniture","modernisierung","magic-marvel","dach","tre"];
const projectBentoClasses={modernisierung:"feature", "magic-marvel":"tall", dach:"tall", tre:"wide"};
const timeline=[
["03.2025 - heute","Master of Arts Innenarchitektur","Hochschule Kaiserslautern","Studium",["Vertiefung Interior Architecture","Raumkonzepte, Materialität und atmosphärische Gestaltung"]],
["08.2023 - heute","Recruiter & HR Administrator","Reline Europe GmbH","Beruf",["Bewerbungsmanagement und Koordination von Gesprächen","Kommunikation mit Bewerbern, HR-Administration"]],
["08.2023 - 03.2024","Auslandspraktikum","D-Eva Studio, Indonesien","Praktikum",["Gestaltung des Beachclubs für Desa Kitsuné","Raumkonzepte und Layouts für Villen","Content-Strategie für Social Media"]],
["05.2023 - 11.2024","Interior Designer / Innenraumausstatterin","Team Rossberg Engineering","Beruf",["Beratung von Kunden und Entwicklung individueller Raumkonzepte","Auswahl, Beschaffung und Visualisierung von Materialien","Koordination und Überwachung von Umsetzungsprojekten"]],
["10.2020 - 03.2025","Bachelor of Arts Innenarchitektur","Hochschule Kaiserslautern","Studium",["Schwerpunkte: Design, Raumplanung, kreative Konzepte","Abschlussarbeit: Modernisierung mit Feingefühl"]],
["08.2020 - heute","Ehrenamtliche Dolmetscherin","Arbeitskreis Humanitäre Hilfe für Asylbewerber e.V.","Ehrenamt",["Dolmetschen bei Terminen mit Ämtern, Ärzten und Helfenden","Unterstützung bei der Verständigung im Alltag Geflüchteter"]],
["2021 - 2023","Servicekraft","Commami","Beruf",["Kundenkontakt und direkter Umgang mit Menschen","Professionelles Verhalten in stressigen Situationen"]],
["2015 - 2017","Rechtswissenschaft","Köln","Studium",["Begonnen, später bewusster Wechsel zur kreativen Leidenschaft Innenarchitektur"]]
];
const software=[["VectorWorks","CAD · Grundrisse, Schnitte, Konstruktionspläne",92],["SketchUp","3D-Modelle, Explosionszeichnungen, Entwürfe",86],["Twinmotion","Innen- & Außenrenderings, Atmosphäre",84],["Adobe Photoshop","Bildbearbeitung, Moodboards, Aufbereitung",76],["Adobe InDesign","Layout, Portfolio, Projektdokumentation",72]];
const clusters=[["Design & Konzept",["Raumkonzepte","Moodboards","Farbtheorie","Materialauswahl","Storytelling","Funktionale Planung"]],["Planung & Visualisierung",["Grundrisse","Schnitte","Renderings","3D-Visualisierung","Lichtkonzepte","Detailzeichnungen"]],["Material & Atmosphäre",["Terrazzo","Holz","Akustikpaneele","Begrünung","Licht","Möbeldesign"]],["Umsetzung & Kommunikation",["Kundenberatung","Projektkoordination","Teamarbeit","HR & Recruiting","Präsentation"]]];
const kindColors={Studium:"#4e0000",Beruf:"#4A6858",Praktikum:"#253328",Ehrenamt:"#B85C38"};
const state={modalId:null,idx:0,filter:"alle",lightbox:null,videoDuration:0,target:0,frame:0,lastSeen:-1};
const $=s=>document.querySelector(s);
const sc=$("#app-scroll"),hero=$("#hero"),video=$("#hero-video"),bar=$("#hero-progress");
function navTo(id){const el=document.getElementById(id);if(!el)return;const top=sc.scrollTop+(el.getBoundingClientRect().top-sc.getBoundingClientRect().top)-64;sc.scrollTo({top,behavior:"smooth"})}
document.querySelectorAll("[data-target]").forEach(b=>b.addEventListener("click",()=>navTo(b.dataset.target)));
function initMarquee(){const track=$("#marquee-track");track.innerHTML=[...marqueeWords,...marqueeWords].map(w=>`<span>${w}</span>`).join("")}
function renderDocs(){const grid=$("#doc-grid");grid.innerHTML=aktDocs.map((d,i)=>`<button class="doc-card" data-doc="${i}"><img src="${d.src}" alt="${d.label}"><div><span>${d.label}</span><small>${d.tag}</small></div></button>`).join("");grid.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>openLightbox(aktDocs[+b.dataset.doc].src,`${aktDocs[+b.dataset.doc].label} · ${aktDocs[+b.dataset.doc].tag}`)))}
function renderProjects(){const grid=$("#project-grid"),ordered=projectBentoOrder.map(id=>projects.find(p=>p.id===id)).filter(Boolean);grid.innerHTML=ordered.map((p,i)=>{const cls=projectBentoClasses[p.id]||"",displayTitle=p.title;return`<div class="project-cell ${cls}" style="--i:${i}"><button class="pc" data-project="${p.id}"><div class="pc-media"><img src="${p.images[0].src}" alt="${displayTitle}" loading="lazy"><div class="pc-hover-overlay"><span class="pc-hover-label">Explore →</span></div><div class="pc-sheen"></div></div><div class="pc-body"><div><div class="pc-kicker">${p.type} · ${p.year}</div><div class="pc-title">${displayTitle}</div><div class="pc-meta">${p.catLabel}</div></div><div class="pc-year">${p.sheet}</div></div>${p.id==="modernisierung"?`<div class="pc-feature-caption"><small>Bachelor-Abschlussarbeit</small><strong>${p.title}</strong><p>${p.blurb}</p></div>`:""}</button></div>`}).join("");grid.querySelectorAll(".pc").forEach(b=>b.addEventListener("click",()=>openProject(b.dataset.project)))}
function renderSkills(){const list=$("#software-list");list.innerHTML=software.map(s=>`<div class="software-row"><header><strong>${s[0]}</strong><span class="skill-pct"><span class="skill-pct-num">0</span><em>%</em></span></header><div class="bar"><span class="bar-fill" style="width:${s[2]}%"></span></div><small class="skill-desc">${s[1]}</small></div>`).join("");$("#cluster-list").innerHTML=clusters.map((c,i)=>`<div class="cat-card" style="--i:${i}"><div class="cat-card-title"><span class="cat-kicker">K${String(i+1).padStart(2,"0")}</span>${c[0]}</div><div class="cat-tags">${c[1].map(t=>`<span>${t}</span>`).join("")}</div></div>`).join("")}
function renderTimeline(){var vp=document.getElementById("wd-viewport");if(!vp)return;vp.innerHTML=timeline.map(function(t,i){var col=kindColors[t[3]]||"#4A6858";return'<div class="timeline-card'+(i===0?" active":"")+'"><div class="tc-kind" style="color:'+col+'">'+t[3]+'</div><h3>'+t[1]+'</h3><p><strong>'+t[0]+'</strong><br>'+t[2]+'</p><ul>'+t[4].map(function(x){return'<li>'+x+'</li>';}).join('')+'</ul></div>';}).join("");var bar=document.getElementById("wd-bar");var yearEl=document.getElementById("wd-year");var currentYear=String(new Date().getFullYear());var years=timeline.map(function(t){var s=String(t[0]);return s.indexOf("heute")!==-1?currentYear:(s.match(/\d{4}/)||["2025"])[0];});function update(){var maxScroll=vp.scrollWidth-vp.clientWidth;var p=maxScroll>0?vp.scrollLeft/maxScroll:0;if(bar)bar.style.width=(p*100).toFixed(1)+"%";var cards=Array.from(vp.querySelectorAll(".timeline-card"));var vpLeft=vp.getBoundingClientRect().left;var activeIdx=0,minD=Infinity;cards.forEach(function(c,i){var d=Math.abs(c.getBoundingClientRect().left-vpLeft);if(d<minD){minD=d;activeIdx=i;}});cards.forEach(function(c,i){c.classList.toggle("active",i===activeIdx);});if(yearEl)yearEl.textContent=years[activeIdx]||"2025";var sec=vp.closest('.werdegang-section');var atEnd=maxScroll<=0||vp.scrollLeft>=maxScroll-12;if(sec)sec.classList.toggle('wd-at-end',atEnd);var hint=document.getElementById('wd-scroll-hint');if(hint)hint.classList.toggle('hidden',atEnd);}vp.addEventListener("scroll",update,{passive:true});var hint=document.createElement('div');hint.id='wd-scroll-hint';hint.className='wd-scroll-hint';hint.innerHTML='<span>Scrollen</span><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M3 9h12M11 5l4 4-4 4" stroke="#7C8A72" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';vp.parentElement.appendChild(hint);update();var drag={on:false,x:0};vp.addEventListener("mousedown",function(e){drag.on=true;drag.x=e.clientX;vp.classList.add("dragging");e.preventDefault();});document.addEventListener("mousemove",function(e){if(!drag.on)return;vp.scrollLeft+=drag.x-e.clientX;drag.x=e.clientX;},{passive:true});document.addEventListener("mouseup",function(){drag.on=false;vp.classList.remove("dragging");});vp.addEventListener("touchstart",function(e){drag.on=true;drag.x=e.touches[0].clientX;},{passive:true});vp.addEventListener("touchmove",function(e){if(!drag.on)return;vp.scrollLeft+=drag.x-e.touches[0].clientX;drag.x=e.touches[0].clientX;},{passive:true});vp.addEventListener("touchend",function(){drag.on=false;});}
function activeProject(){return projects.find(p=>p.id===state.modalId)}
function visibleImages(){const p=activeProject();if(!p)return[];return state.filter==="alle"?p.images:p.images.filter(im=>im.cat===state.filter)}
function openProject(id){state.modalId=id;state.idx=0;state.filter="alle";document.body.style.overflow="hidden";renderModal()}
function closeProject(){state.modalId=null;document.body.style.overflow="";$("#project-modal").classList.remove("open");$("#project-modal").setAttribute("aria-hidden","true")}
function setFilter(f){state.filter=f;state.idx=0;renderModal()}
function stepImg(dir){const v=visibleImages();if(v.length){state.idx=(state.idx+dir+v.length)%v.length;renderModal()}}
function stepProject(dir){const i=projects.findIndex(p=>p.id===state.modalId);state.modalId=projects[(i+dir+projects.length)%projects.length].id;state.idx=0;state.filter="alle";renderModal()}
function renderModal(){const p=activeProject();if(!p)return;const modal=$("#project-modal"),imgs=visibleImages(),current=imgs[state.idx]||imgs[0];const cats=["alle",...["rendering","plan","modell","detail"].filter(c=>p.images.some(im=>im.cat===c))];modal.innerHTML=`<div class="modal-panel"><div class="modal-media"><button class="modal-close" id="modal-close">Schließen ✕</button><button class="modal-arrow prev" id="prev-img">‹</button><img src="${current.src}" alt="${current.label}"><button class="modal-arrow next" id="next-img">›</button></div><aside class="modal-info"><div class="section-kicker">${p.sheet} · ${p.catLabel}</div><h2>${p.title}</h2><p><strong>${p.year}</strong> · ${p.role}<br>${p.place}</p><p>${p.concept}</p><div class="filter-row">${cats.map(c=>`<button class="${state.filter===c?"active":""}" data-filter="${c}">${c==="alle"?"Alle":catMeta[c].label.split(" ")[0]}</button>`).join("")}</div><p><strong>${current.label}</strong> · ${state.idx+1} / ${imgs.length}</p><div class="thumb-row">${imgs.map((im,i)=>`<button class="thumb ${i===state.idx?"active":""}" data-thumb="${i}"><img src="${im.src}" alt="${im.label}"></button>`).join("")}</div><h3>Maßnahmen</h3><ul class="detail-list">${p.measures.map(m=>`<li>${m}</li>`).join("")}</ul><h3>Material & Tools</h3><div class="pill-list">${[...p.materials,...p.programs].map(m=>`<span>${m}</span>`).join("")}</div><h3>Ergebnis</h3><p>${p.result}</p><div class="hero-actions"><button class="secondary" id="prev-project">Vorheriges Projekt</button><button class="primary" id="next-project">Nächstes Projekt</button></div></aside></div>`;modal.classList.add("open");modal.setAttribute("aria-hidden","false");$("#modal-close").onclick=closeProject;$("#prev-img").onclick=()=>stepImg(-1);$("#next-img").onclick=()=>stepImg(1);$("#prev-project").onclick=()=>stepProject(-1);$("#next-project").onclick=()=>stepProject(1);modal.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>setFilter(b.dataset.filter));modal.querySelectorAll("[data-thumb]").forEach(b=>b.onclick=()=>{state.idx=+b.dataset.thumb;renderModal()})}
function openLightbox(src,label){const lb=$("#lightbox");state.lightbox=src;document.body.style.overflow="hidden";lb.innerHTML=`<div class="lightbox-inner"><div class="lightbox-top"><span>${label}</span><button id="close-lightbox">Schließen ✕</button></div><img src="${src}" alt="${label}"></div>`;lb.classList.add("open");lb.setAttribute("aria-hidden","false");$("#close-lightbox").onclick=closeLightbox}
function waldVisible(){return state.waldTab==="alle"?waldAssets:waldAssets.filter(x=>x.tab===state.waldTab)}
function openWaldModal(tab="fotos"){state.waldTab=tab;state.waldIdx=0;document.body.style.overflow="hidden";renderWaldModal()}
function renderWaldModal(){const lb=$("#lightbox"),tabs=[["alle","Alle"],["fotos","Fotos"],["grundrisse","Grundrisse"],["schnitte","Schnitte"]],items=waldVisible(),current=items[state.waldIdx]||items[0];state.lightbox=current.src;lb.innerHTML=`<div class="wald-modal-panel"><button class="wald-modal-close" id="close-lightbox">x</button><div class="wald-modal-head"><small>Aktuelles - laufende Masterarbeit</small><strong>Waldmannsburg</strong></div><div class="wald-tabs">${tabs.map(t=>`<button class="wald-tab ${state.waldTab===t[0]?"active":""}" data-tab="${t[0]}">${t[1]}</button>`).join("")}</div><figure class="wald-modal-stage"><img class="wald-modal-image" src="${current.src}" alt="${current.label}" loading="lazy"><figcaption>${current.label}</figcaption></figure><div class="wald-modal-controls"><button id="wald-prev">Prev</button><span>${state.waldIdx+1} / ${items.length}</span><button id="wald-next">Naechstes</button></div></div>`;lb.classList.add("open");lb.setAttribute("aria-hidden","false");$("#close-lightbox").onclick=closeLightbox;$("#wald-prev").onclick=()=>{state.waldIdx=(state.waldIdx-1+items.length)%items.length;renderWaldModal()};$("#wald-next").onclick=()=>{state.waldIdx=(state.waldIdx+1)%items.length;renderWaldModal()};lb.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{state.waldTab=b.dataset.tab;state.waldIdx=0;renderWaldModal()})}
function openDocsOverlay(){openWaldModal("grundrisse")}
function renderDocs(){const open=$("#open-docs"),wald=$("#open-wald-modal");if(open)open.addEventListener("click",openDocsOverlay);if(wald)wald.addEventListener("click",()=>openWaldModal("fotos"));const grid=$("#doc-grid");if(grid)grid.innerHTML=""}
function closeLightbox(){state.lightbox=null;document.body.style.overflow="";$("#lightbox").classList.remove("open");$("#lightbox").setAttribute("aria-hidden","true")}
function computeHero(){const total=hero.offsetHeight-sc.clientHeight;let p=total>0?sc.scrollTop/total:0;p=Math.max(0,Math.min(1,p));const dur=state.videoDuration||video.duration||0;state.target=dur?p*Math.max(0,dur-.04):0;bar.style.transform=`scaleX(${p.toFixed(4)})`}
function driveVideo(){if(!video||video.readyState<2)return;const diff=state.target-video.currentTime;const adiff=Math.abs(diff);if(adiff<.05){if(!video.paused)video.pause();return}if(diff>0){video.playbackRate=Math.min(9,Math.max(1,diff*4));if(video.paused){const pr=video.play();if(pr&&pr.catch)pr.catch(()=>{})}}else{if(!video.paused)video.pause();try{video.currentTime=video.currentTime+diff*.3}catch(e){}}}
function layoutTimeline(){}
function scrubTimeline(){}
function loop(){state.frame++;computeHero();driveVideo();requestAnimationFrame(loop)}
video.addEventListener("loadedmetadata",()=>{state.videoDuration=video.duration||0;try{video.currentTime=0;video.pause()}catch(e){}});
sc.addEventListener("scroll",()=>{computeHero();if(state.frame===state.lastSeen&&video.readyState>=1){try{video.pause();video.currentTime=state.target}catch(e){}}state.lastSeen=state.frame},{passive:true});
addEventListener("resize",()=>{layoutTimeline();computeHero()},{passive:true});
addEventListener("keydown",e=>{if(e.key==="Escape"){closeProject();closeLightbox()}if(state.modalId&&e.key==="ArrowRight")stepImg(1);if(state.modalId&&e.key==="ArrowLeft")stepImg(-1)});
$("#copy-email").addEventListener("click",async()=>{try{await navigator.clipboard.writeText("schabnam.shor@googlemail.com");$("#copy-feedback").textContent="Kopiert ✓"}catch(e){$("#copy-feedback").textContent="Kopieren"}setTimeout(()=>$("#copy-feedback").textContent="Kopieren",1900)});
(function(){
  var form=document.getElementById('contact-form');
  var btn=document.getElementById('cf-btn');
  var successEl=document.getElementById('cf-success');
  var errorEl=document.getElementById('cf-error');
  var resetBtn=document.getElementById('cf-reset');
  if(!form)return;
  form.addEventListener('submit',function(e){
    e.preventDefault();
    errorEl.textContent='';
    btn.disabled=true;
    btn.textContent='Wird gesendet…';
    fetch('https://formspree.io/f/meebjejp',{
      method:'POST',
      headers:{'Accept':'application/json'},
      body:new FormData(form)
    })
    .then(function(res){return res.json().then(function(data){return{ok:res.ok,data:data};});})
    .then(function(result){
      if(result.ok){
        form.querySelectorAll('input,textarea').forEach(function(el){el.value='';});
        btn.style.display='none';
        successEl.classList.add('visible');
      } else {
        var msg=result.data&&result.data.errors?result.data.errors.map(function(e){return e.message;}).join(' · '):'Fehler beim Senden. Bitte erneut versuchen.';
        errorEl.textContent=msg;
        btn.disabled=false;
        btn.textContent='Erneut versuchen';
      }
    })
    .catch(function(){
      errorEl.textContent='Netzwerkfehler. Bitte erneut versuchen.';
      btn.disabled=false;
      btn.textContent='Erneut versuchen';
    });
  });
  if(resetBtn){resetBtn.addEventListener('click',function(){successEl.classList.remove('visible');btn.style.display='';btn.disabled=false;btn.textContent='Nachricht senden';});}
})();
function initTypewriter(){var h2=document.querySelector('.typewriter-h2');if(!h2)return;var tw=h2.querySelector('.tw-text');var cursor=h2.querySelector('.tw-cursor');if(!tw||!cursor)return;var text=h2.dataset.tw||'';var i=0;function type(){if(i<=text.length){tw.textContent=text.slice(0,i);i++;setTimeout(type,i===text.length+1?700:58);}else{setTimeout(function(){if(cursor){cursor.style.animation='none';cursor.style.opacity='0';}},2400);}}var started=false;var obs=new IntersectionObserver(function(entries){if(entries[0].isIntersecting&&!started){started=true;obs.disconnect();setTimeout(type,320);}},{threshold:0.35,root:sc});obs.observe(h2);}
function initSkillsAnim(){
var sec=document.getElementById('faehigkeiten');
if(!sec)return;
var done=false;
var easeOut=function(t){return 1-Math.pow(1-t,3);};
var obs=new IntersectionObserver(function(entries){
  if(entries[0].isIntersecting&&!done){
    done=true;obs.disconnect();
    var rows=sec.querySelectorAll('.software-row');
    rows.forEach(function(row,idx){
      var tgt=software[idx]?software[idx][2]:0;
      var numEl=row.querySelector('.skill-pct-num');
      var barEl=row.querySelector('.bar-fill');
      var dur=1500;
      setTimeout(function(){
        if(barEl)barEl.style.transform='scaleX(1)';
        var t0=null;
        var tick=function(ts){
          if(!t0)t0=ts;
          var prog=Math.min((ts-t0)/dur,1);
          if(numEl)numEl.textContent=Math.round(easeOut(prog)*tgt);
          if(prog<1)requestAnimationFrame(tick);
        };
        requestAnimationFrame(tick);
      },idx*80);
    });
  }
},{threshold:0.2,root:sc});
obs.observe(sec);
}
initMarquee();renderDocs();renderProjects();renderSkills();initSkillsAnim();renderTimeline();initTypewriter();computeHero();requestAnimationFrame(loop);
(function(){
  var btn=document.getElementById('mobile-menu-btn');
  var nav=document.getElementById('mobile-nav');
  if(!btn||!nav)return;
  function openMenu(){btn.classList.add('open');nav.classList.add('open');nav.setAttribute('aria-hidden','false');btn.setAttribute('aria-expanded','true');document.body.style.overflow='hidden';}
  function closeMenu(){btn.classList.remove('open');nav.classList.remove('open');nav.setAttribute('aria-hidden','true');btn.setAttribute('aria-expanded','false');document.body.style.overflow='';}
  btn.addEventListener('click',function(){btn.classList.contains('open')?closeMenu():openMenu();});
  nav.querySelectorAll('[data-target]').forEach(function(el){el.addEventListener('click',function(){navTo(el.dataset.target);closeMenu();});});
})();
